const libraries = [
  {
    name: 'svelte-typewriter',
    url: 'https://github.com/henriquehbr/svelte-typewriter',
    tags: ['svelte', 'typewriter-effect'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-websocket-store',
    url: 'https://github.com/arlac77/svelte-websocket-store',
    tags: ['components', 'store'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-tags-input',
    url: 'https://github.com/agustinl/svelte-tags-input',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'carbon-components-svelte',
    url: 'https://github.com/IBM/carbon-components-svelte',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelma',
    url: 'https://github.com/c0bra/svelma',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'smelte',
    url: 'https://github.com/matyunya/smelte',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-toolbox',
    url: 'https://github.com/svelte-toolbox/svelte-toolbox',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-material-ui',
    url: 'https://github.com/hperrin/svelte-material-ui',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelteify',
    url: 'https://github.com/exybore/svelteify',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltemantic',
    url: 'https://github.com/titans-inc/sveltemantic',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltestrap',
    url: 'https://github.com/bestguy/sveltestrap',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-ui',
    url: 'https://github.com/vikignt/svelte-ui',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svmd',
    url: 'https://github.com/hkh12/svmd',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-chota',
    url: 'https://github.com/alexxnb/svelte-chota',
    tags: ['components', 'ui component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@zooplus/zoo-web-components',
    url: 'https://github.com/zooplus/zoo-web-components',
    tags: ['components', 'web component sets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/svelte-virtual-list',
    url: 'https://github.com/sveltejs/svelte-virtual-list',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/svelte-scroller',
    url: 'https://github.com/sveltejs/svelte-scroller',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/svelte-subdivide',
    url: 'https://github.com/sveltejs/svelte-subdivide',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-grid',
    url: 'https://github.com/vaheqelyan/svelte-grid',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-sortable-list',
    url: 'https://github.com/brunomolteni/svelte-sortable-list',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-carousel',
    url: 'https://github.com/beyonk-adventures/svelte-carousel',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'multicarousel',
    url: 'https://github.com/sciactive/multicarousel',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-swipe',
    url: 'https://github.com/SharifClick/svelte-swipe',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-tabs',
    url: 'https://github.com/joeattardi/svelte-tabs',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-media-query',
    url: 'https://github.com/xelaok/svelte-media-query',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-match-media',
    url: 'https://github.com/pearofducks/svelte-match-media',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-watch-resize',
    url: 'https://github.com/xelaok/svelte-watch-resize',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-simple-modal',
    url: 'https://github.com/flekschas/svelte-simple-modal',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-popover',
    url: 'https://github.com/vaheqelyan/svelte-popover',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-headroom',
    url: 'https://github.com/collardeau/svelte-headroom',
    tags: ['components', 'layout and structure'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/svelte-repl',
    url: 'https://github.com/sveltejs/svelte-repl',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-color-picker',
    url: 'https://github.com/qintarp/svelte-color-picker',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-select',
    url: 'https://github.com/rob-balfre/svelte-select',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-rate-it',
    url: 'https://github.com/emrekara37/svelte-rate-it',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'waxwing-rating',
    url: 'https://github.com/dmitrykurmanov/waxwing-rating',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/gdpr-cookie-consent-banner',
    url: 'https://github.com/beyonk-adventures/gdpr-cookie-consent-banner',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-inspect',
    url: 'https://github.com/trbrc/svelte-inspect',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@okrad/svelte-progressbar',
    url: 'https://github.com/okrad/svelte-progressbar',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Browser REPL JS',
    url: 'https://github.com/milafrerichs/browser-repl-js',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Simple Svelte Autocomplete',
    url: 'https://github.com/pstanoev/simple-svelte-autocomplete',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-ruler',
    url: 'https://github.com/daybrush/ruler/tree/master/packages/svelte-ruler',
    tags: ['components', 'inputs and widgets'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-icons',
    url: 'https://github.com/gibdig/svelte-icons',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-awesome',
    url: 'https://github.com/RobBrazier/svelte-awesome',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-fa',
    url: 'https://github.com/Cweili/svelte-fa',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'fa-svelte',
    url: 'https://github.com/alphapeter/fa-svelte',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-feather-icons',
    url: 'https://github.com/dylanblokhuis/svelte-feather-icons',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-simple-icons',
    url: 'https://github.com/beyonk-adventures/svelte-simple-icons',
    tags: ['components', 'fonts and icons'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@spaceavocado/svelte-form',
    url: 'https://github.com/spaceavocado/svelte-form',
    tags: ['components', 'forms and validation'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-forms',
    url: 'https://github.com/chainlist/svelte-forms',
    tags: ['components', 'forms and validation'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-forms-lib',
    url: 'https://github.com/tjinauyeung/svelte-forms-lib',
    tags: ['components', 'forms and validation'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs-forms',
    url: 'https://github.com/mdauner/sveltejs-forms',
    tags: ['components', 'forms and validation'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-waypoint',
    url: 'https://github.com/matyunya/svelte-waypoint',
    tags: ['components', 'images'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-image',
    url: 'https://github.com/matyunya/svelte-image',
    tags: ['components', 'images'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-image-encoder',
    url: 'https://github.com/saabi/svelte-image-encoder',
    tags: ['components', 'images'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-marquee',
    url: 'https://github.com/silvestrevivo/svelte-marquee',
    tags: ['components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-easy-crop',
    url: 'https://github.com/ValentinH/svelte-easy-crop',
    tags: ['components', 'images'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'echarts-for-svelte',
    url: 'https://github.com/liyuanqiu/echarts-for-svelte',
    tags: ['components', 'charts'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-fusioncharts',
    url: 'https://github.com/priyanjitdey94/svelte-fusioncharts',
    tags: ['components', 'charts'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-calendar',
    url: 'https://github.com/6eDesign/svelte-calendar',
    tags: ['components', 'time and date'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-flatpickr',
    url: 'https://github.com/jacobmischka/svelte-flatpickr',
    tags: ['components', 'time and date'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-notifications',
    url: 'https://github.com/beyonk-adventures/svelte-notifications',
    tags: ['components', 'notifications'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-notifications',
    url: 'https://github.com/keenethics/svelte-notifications',
    tags: ['components', 'notifications'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-mapbox',
    url: 'https://github.com/beyonk-adventures/svelte-mapbox',
    tags: ['components', 'maps'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-googlemaps',
    url: 'https://github.com/beyonk-adventures/svelte-googlemaps',
    tags: ['components', 'maps'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-pick-a-place',
    url: 'https://github.com/jimutt/svelte-pick-a-place',
    tags: ['components', 'maps'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-i18n',
    url: 'https://github.com/kaisermann/svelte-i18n',
    tags: ['components', 'internationalization'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-intl',
    url: 'https://github.com/Panya/svelte-intl',
    tags: ['components', 'internationalization'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-writable-derived',
    url: 'https://github.com/PikadudeNo1/svelte-writable-derived',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-apollo',
    url: 'https://github.com/timhall/svelte-apollo',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Svelte for Meteor',
    url: 'https://github.com/meteor-svelte/meteor-svelte',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-webext-storage-adapter',
    url: 'https://github.com/PikadudeNo1/svelte-webext-storage-adapter',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-observable',
    url: 'https://github.com/timhall/svelte-observable',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-mobx',
    url: 'https://github.com/xelaok/svelte-mobx',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-redux-connect',
    url: 'https://github.com/kolodziejczak-sz/svelte-redux-connect',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svql',
    url: 'https://github.com/pateketrueke/svql',
    tags: ['components', 'stores and state'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/gestures',
    url: 'https://github.com/sveltejs/gestures',
    tags: ['components', 'interaction'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-scrollspy',
    url: 'https://github.com/beyonk-adventures/svelte-scrollspy',
    tags: ['components', 'interaction'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-moveable',
    url:
      'https://github.com/daybrush/moveable/tree/master/packages/svelte-moveable',
    tags: ['components', 'interaction'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-loadable',
    url: 'https://github.com/kaisermann/svelte-loadable',
    tags: ['components', 'async loading'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-content-loader',
    url: 'https://github.com/PaulMaly/svelte-content-loader',
    tags: ['components', 'async loading'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-viewpoint',
    url: 'https://github.com/PaulMaly/svelte-viewpoint',
    tags: ['components', 'async loading'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-google-analytics',
    url: 'https://github.com/beyonk-adventures/svelte-google-analytics',
    tags: ['components', 'other'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-facebook-pixel',
    url: 'https://github.com/beyonk-adventures/svelte-facebook-pixel',
    tags: ['components', 'other'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-facebook-customer-chat',
    url: 'https://github.com/beyonk-adventures/svelte-facebook-customer-chat',
    tags: ['components', 'other'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@beyonk/svelte-trustpilot',
    url: 'https://github.com/beyonk-adventures/svelte-trustpilot',
    tags: ['components', 'other'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Svelte DevTools',
    url: 'https://github.com/RedHatter/svelte-devtools',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltedoc-parser',
    url: 'https://github.com/alexprey/sveltedoc-parser',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'prettier-plugin-svelte',
    url: 'https://github.com/UnwrittenFun/prettier-plugin-svelte',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-inspector',
    url: 'https://github.com/qutran/svelte-inspector',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-dev-helper',
    url: 'https://github.com/ekhaled/svelte-dev-helper',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@svelte-docs/core',
    url: 'https://github.com/AlexxNB/svelte-docs',
    tags: ['components', 'development'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-adapter',
    url: 'https://github.com/pngwn/svelte-adapter',
    tags: ['components', 'other components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-css-vars',
    url: 'https://github.com/kaisermann/svelte-css-vars',
    tags: ['components', 'other components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs/template',
    url: 'https://github.com/sveltejs/template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs/template-webpack',
    url: 'https://github.com/sveltejs/template-webpack',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs/component-template',
    url: 'https://github.com/sveltejs/component-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs/template-custom-element',
    url: 'https://github.com/sveltejs/template-custom-element',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'sveltejs/sapper-template',
    url: 'https://github.com/sveltejs/sapper-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'dafn/svelte-typescript-rollup',
    url: 'https://github.com/dafn/svelte-typescript-rollup',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'dafn/svelte-typescript-parcel',
    url: 'https://github.com/dafn/svelte-typescript-parcel',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'pyoner/svelte-typescript',
    url: 'https://github.com/pyoner/svelte-typescript',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Axelen123/svelte-ts-template',
    url: 'https://github.com/Axelen123/svelte-ts-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Shyam-Chen/svelte-play',
    url: 'https://github.com/Shyam-Chen/Svelte-Play',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Holben888/svelte-starter-template',
    url: 'https://github.com/Holben888/svelte-starter-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'marcograhl/tailwindcss-svelte-starter',
    url: 'https://github.com/marcograhl/tailwindcss-svelte-starter',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'muhajirdev/svelte-tailwind-template',
    url: 'https://github.com/muhajirdev/svelte-tailwind-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'fabiohvp/svelte-template',
    url: 'https://github.com/fabiohvp/svelte-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'justinekizhak/svelte-tailwind-template',
    url: 'https://github.com/justinekizhak/svelte-tailwind-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'geakstr/svelte-3-rollup-typescript-vscode',
    url: 'https://github.com/geakstr/svelte-3-rollup-typescript-vscode',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'jorgegorka/svelte-firebase',
    url: 'https://github.com/jorgegorka/svelte-firebase',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'ricalamino/svelte-firebase-auth',
    url: 'https://github.com/ricalamino/svelte-firebase-auth',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'YogliB/svelte-component-template',
    url: 'https://github.com/YogliB/svelte-component-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'neighbourhoodie/svelte-pouchdb-couchdb',
    url: 'https://github.com/neighbourhoodie/svelte-pouchdb-couchdb',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'OrdinaryJellyfish/svelte-routing-template',
    url: 'https://github.com/OrdinaryJellyfish/svelte-routing-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'angelozehr/svelte-example-museums',
    url: 'https://github.com/angelozehr/svelte-example-museums',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'pankod/svelte-boilerplate',
    url: 'https://github.com/pankod/svelte-boilerplate',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'pbastowski/svelte-poi-starter',
    url: 'https://github.com/pbastowski/svelte-poi-starter',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'soapdog/svelte-template-browserify',
    url: 'https://github.com/soapdog/svelte-template-browserify',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'antony/svelte-box',
    url: 'https://github.com/antony/svelte-box',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'spaceavocado/svelte-router-template',
    url: 'https://github.com/spaceavocado/svelte-router-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'beyonk-adventures/svelte-component-livereload-template',
    url:
      'https://github.com/beyonk-adventures/svelte-component-livereload-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'patoi/svelte-component-library-template',
    url: 'https://github.com/patoi/svelte-component-library-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'brandonxiang/svelte-webpack-mpa',
    url: 'https://github.com/brandonxiang/svelte-webpack-mpa',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'jerriclynsjohn/svelte-storybook-tailwind',
    url: 'https://github.com/jerriclynsjohn/svelte-storybook-tailwind',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'farhan2106/svelte-typescript',
    url: 'https://github.com/farhan2106/svelte-typescript',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'farhan2106/svelte-typescript-ssr',
    url: 'https://github.com/farhan2106/svelte-typescript-ssr',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'n0th1ng-else/svelte-typescript-sass',
    url: 'https://github.com/n0th1ng-else/svelte-typescript-sass',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'stephanepericat/svelte-boilerplate',
    url: 'https://github.com/stephanepericat/svelte-boilerplate',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'will-wow/svelte-typescript-template',
    url: 'https://github.com/will-wow/svelte-typescript-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'tonyrewin/svelte3-ts-boilerplate',
    url: 'https://github.com/tonyrewin/svelte3-ts-boilerplate',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'devghost/svelte',
    url: 'https://github.com/devghost/svelte',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'SteveALee/svelte-code-cypress-project',
    url: 'https://github.com/SteveALee/svelte-code-cypress-project',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'rixo/svelte-template-hot',
    url: 'https://github.com/rixo/svelte-template-hot',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'agusID/boilerplate-svelte',
    url: 'https://github.com/agusID/boilerplate-svelte',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'LunaTK/svelte-web-component-builder',
    url: 'https://github.com/LunaTK/svelte-web-component-builder',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'nitro52/svelte-typescript-sass-template',
    url: 'https://github.com/nitro52/svelte-typescript-sass-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Rich-Harris/svelte-template-electron',
    url: 'https://github.com/Rich-Harris/svelte-template-electron',
    tags: ['templates', 'electron templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Blade67/Sveltron',
    url: 'https://github.com/Blade67/Sveltron',
    tags: ['templates', 'electron templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'chuanqisun/svelte-electron-template',
    url: 'https://github.com/chuanqisun/svelte-electron-template',
    tags: ['templates', 'electron templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'syonip/svelte-cordova',
    url: 'https://github.com/syonip/svelte-cordova',
    tags: ['templates', 'mobile templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'lpshanley/svelte-phonegap',
    url: 'https://github.com/lpshanley/svelte-phonegap',
    tags: ['templates', 'mobile templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@testing-library/svelte',
    url: 'https://github.com/testing-library/svelte-testing-library',
    tags: ['testing'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'jest-transform-svelte',
    url: 'https://github.com/rspieker/jest-transform-svelte',
    tags: ['testing'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-test',
    url: 'https://github.com/pngwn/svelte-test',
    tags: ['testing'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'storybookjs',
    url: 'https://github.com/storybookjs/storybook',
    tags: ['testing'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-jest',
    url: 'https://github.com/ktsn/svelte-jest',
    tags: ['testing'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-routing',
    url: 'https://github.com/EmilTholin/svelte-routing',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-state-renderer',
    url: 'https://github.com/TehShrike/svelte-state-renderer',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-spa-router',
    url: 'https://github.com/ItalyPaleAle/svelte-spa-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svero',
    url: 'https://github.com/kazzkiq/svero',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'swheel',
    url: 'https://github.com/qutran/swheel',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@jamen/svelte-router',
    url: 'https://github.com/jamen/svelte-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-hash-router',
    url: 'https://github.com/pynnl/svelte-hash-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-easyroute',
    url: 'https://github.com/lyohaplotinka/svelte-easyroute',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-router-spa',
    url: 'https://github.com/jorgegorka/svelte-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@spaceavocado/svelte-router',
    url: 'https://github.com/spaceavocado/svelte-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-page-router',
    url: 'https://github.com/PaulMaly/svelte-page-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-router',
    url: 'https://github.com/jikkai/svelte-router',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-navaid',
    url: 'https://github.com/jacwright/svelte-navaid',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@slick-for/svelte',
    url: 'https://github.com/shavyg2/slick-for-svelte',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'crayon-svelte',
    url: 'https://github.com/alshdavid/crayon',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'routify',
    url: 'https://github.com/sveltech/routify',
    tags: ['routers', 'ssr'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'yrv',
    url: 'https://github.com/pateketrueke/yrv',
    tags: ['routers'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-loader',
    url: 'https://github.com/sveltejs/svelte-loader',
    tags: ['integrations', 'bundler plugins'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'rollup-plugin-svelte',
    url: 'https://github.com/rollup/rollup-plugin-svelte',
    tags: ['integrations', 'bundler plugins'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelvet',
    url: 'https://github.com/jakedeichert/svelvet',
    tags: ['integrations', 'bundler plugins'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-preprocess',
    url: 'https://github.com/kaisermann/svelte-preprocess',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'mdsvex',
    url: 'https://github.com/pngwn/MDsveX',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-preprocess-markdown',
    url: 'https://github.com/AlexxNB/svelte-preprocess-markdown',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-ts-preprocess',
    url: 'https://github.com/PaulMaly/svelte-ts-preprocess',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@pyoner/svelte-ts-preprocess',
    url: 'https://github.com/pyoner/svelte-typescript',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-preprocess-postcss',
    url: 'https://github.com/TehShrike/svelte-preprocess-postcss',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-preprocess-sass',
    url: 'https://github.com/ls-age/svelte-preprocess-sass',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-preprocess-less',
    url: 'https://github.com/ls-age/svelte-preprocess-less',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@modular-css/svelte',
    url: 'https://github.com/tivac/modular-css/tree/master/packages/svelte',
    tags: ['integrations', 'preprocessors'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@pwa/cli',
    url: 'https://github.com/lukeed/pwa',
    tags: ['integrations', 'cli tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'baelte',
    url: 'https://github.com/kennethlarsen/baelte',
    tags: ['integrations', 'cli tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svb',
    url: 'https://github.com/himynameisdave/svb',
    tags: ['integrations', 'cli tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-vscode',
    url: 'https://github.com/UnwrittenFun/svelte-vscode',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'vim-svelte',
    url: 'https://github.com/evanleck/vim-svelte',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'vim-svelte-plugin',
    url: 'https://github.com/leafOfTree/vim-svelte-plugin',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-mode',
    url: 'https://github.com/leafOfTree/svelte-mode',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-intellij',
    url: 'https://github.com/tomblachut/svelte-intellij',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-language-server',
    url: 'https://github.com/UnwrittenFun/svelte-language-server',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'vscode-svelte-component-extractor',
    url:
      'https://github.com/proverbial-ninja/vscode-svelte-component-extractor',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'coc-svelte',
    url: 'https://github.com/coc-extensions/coc-svelte',
    tags: ['integrations', 'editor tools'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-native',
    url: 'https://github.com/halfnelson/svelte-native',
    tags: ['native'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@sveltejs/gl',
    url: 'https://github.com/sveltejs/gl',
    tags: ['experiments'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-frappe-charts',
    url: 'https://github.com/himynameisdave/svelte-frappe-charts',
    tags: ['charts', 'components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-fullcalendar',
    url: 'https://github.com/YogliB/svelte-fullcalendar',
    tags: ['components', 'time and date'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-component-template',
    url: 'https://github.com/YogliB/svelte-component-template',
    tags: ['templates'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelidation',
    url: 'https://github.com/yazonnile/svelidation',
    tags: ['components', 'forms and validation'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'Ionic Svelte UI demo',
    url: 'https://github.com/Tommertom/svelte-ionic-app',
    tags: [
      'components',
      'ui component sets',
      'web component sets',
      'mobile templates',
    ],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: '@dopry/svelte-auth0',
    url: 'https://github.com/dopry/svelte-auth0',
    tags: ['components', 'integrations', 'auth'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-multitoneimage',
    url: 'https://github.com/stephane-vanraes/svelte-multitoneimage',
    tags: ['components', 'images'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-progresscircle',
    url: 'https://github.com/stephane-vanraes/svelte-progresscircle',
    tags: ['components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'svelte-eventbus',
    url: 'https://github.com/AlexxNB/svelte-eventbus',
    tags: ['components'],
    tests: 'pending',
    examples: 'pending',
    apiDoc: 'pending',
    CIsetup: 'pending',
  },
  {
    name: 'nye/svelte-electron-better-sqlite3-starter',
    url: 'https://github.com/nye/svelte-electron-better-sqlite3-starter',
    examples: 'pending',
    apiDoc: 'pending',
    CI: 'pending',
    tags: ['templates', 'electron', 'database'],
  },
];

export default libraries;
